apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-service
  template:
    metadata:
      labels:
        app: rest-service
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name : rest-service
        image: fardreamer/rest_service:latest
        ports:
        - containerPort: 8080
          name         : rest-service
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: rest-service
spec:
  type: LoadBalancer
  ports:
  - name      : app-listener
    port      : 8080
    targetPort: 8080
  selector:
    app: rest-service

